name: Update Release on Push

on:
  push:
    branches: main  # 替换为你的分支

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # 关键权限声明
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 使用最新版本
      
    - name: Create/Update Release
      uses: ncipollo/release-action@v1
      with:
        tag: v1.0.0  # 替换为实际标签
        name: "Release ${{ github.ref_name }}"
        body: ${{ github.event.head_commit.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
