name: Incremental Release Assets

on:
  push:
    branches: main

jobs:
  add-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # 获取上次的构建编号
    - name: Get last build number
      id: build-number
      run: |
        # 这里使用简单计数器文件
        if [ -f build-counter.txt ]; then
          COUNTER=$(($(cat build-counter.txt) + 1))
        else
          COUNTER=1
        fi
        echo $COUNTER > build-counter.txt
        echo "build_number=$COUNTER" >> $GITHUB_OUTPUT
        git add build-counter.txt
        git commit -m "Increment build counter" || echo "No changes"
        git push
        
    # 创建新文件
    - name: Create new asset
      run: |
        mkdir -p release-assets
        echo "Build #${{ steps.build-number.outputs.build_number }}" > \
          "release-assets/v1.0.0-build-${{ steps.build-number.outputs.build_number }}.txt"
          
    # 添加到Release
    - name: Add to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        files: "release-assets/v1.0.0-build-*.txt"
        overwrite: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
